#!/usr/bin/env python3
"""Compose a private CPU Notebook for one pinned public CodeParrot cohort.

This public bridge script is self-contained from public Hugging Face inputs. It
never reads a private GitHub repository and does not contain model-scoring or
competition-attack source. The generated Notebook exports only a label-free
prediction input, a content-free prediction manifest, and aggregate audit data.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import textwrap

import nbformat

MEMBER_DATASET = "codeparrot/codeparrot-clean-train"
MEMBER_REVISION = "3e6ab65f2864931e041f6a82db9b5a6ec2b71ab4"
NONMEMBER_DATASET = "codeparrot/codeparrot-clean-valid"
NONMEMBER_REVISION = "4db92d2ec0c1b4c41eeb439cfae16854511d9dcd"
TARGET = "renta0426/codeparrot-fresh-cohort-v1"
TITLE = "CodeParrot Fresh Cohort V1"
ROWS_PER_LABEL = 2_000
TRAIN_SCAN_ROWS = 500_000

FORBIDDEN_PUBLIC_TRANSPORT = (
    "RESEARCH_REPO_READ_TOKEN",
    "GITHUB_PAT",
    "GH_TOKEN",
    "SSH_PRIVATE_KEY",
    "api.github.com/repos/",
)


def _runtime_cell() -> str:
    return textwrap.dedent(
        f'''
        from collections import defaultdict
        from hashlib import sha256
        from pathlib import Path
        import json
        import math
        import time

        import datasets
        import pandas as pd
        from datasets import load_dataset

        MEMBER_DATASET = {MEMBER_DATASET!r}
        MEMBER_REVISION = {MEMBER_REVISION!r}
        NONMEMBER_DATASET = {NONMEMBER_DATASET!r}
        NONMEMBER_REVISION = {NONMEMBER_REVISION!r}
        ROWS_PER_LABEL = {ROWS_PER_LABEL}
        TRAIN_SCAN_ROWS = {TRAIN_SCAN_ROWS}
        MIN_CHARS = 512
        MAX_CHARS = 32768
        MAX_PER_REPO = 2
        OUTPUT = Path("/kaggle/working/codeparrot_fresh_cohort_v1")
        OUTPUT.mkdir(parents=True, exist_ok=True)

        def digest_text(value):
            return sha256(value.encode("utf-8")).hexdigest()

        def copies_one(value):
            if isinstance(value, bool):
                return False
            try:
                return int(str(value).strip()) == 1
            except Exception:
                return False

        def length_bucket(length):
            return min(14, max(9, int(math.floor(math.log2(length)))))

        def stream(dataset_id, revision):
            return load_dataset(
                dataset_id,
                split="train",
                streaming=True,
                revision=revision,
            )

        def scan(dataset_id, revision, membership, max_rows):
            by_repo = defaultdict(list)
            all_hashes = set()
            scanned = 0
            eligible = 0
            duplicates = 0
            for position, record in enumerate(stream(dataset_id, revision)):
                if max_rows is not None and position >= max_rows:
                    break
                scanned += 1
                content = record.get("content")
                repo = record.get("repo_name")
                path = record.get("path")
                license_name = record.get("license")
                if not isinstance(content, str) or not (MIN_CHARS <= len(content) <= MAX_CHARS):
                    continue
                if record.get("autogenerated") is not False or not copies_one(record.get("copies")):
                    continue
                if not all(isinstance(value, str) and value.strip() for value in (repo, path, license_name)):
                    continue
                content_hash = digest_text(content)
                if content_hash in all_hashes:
                    duplicates += 1
                    continue
                all_hashes.add(content_hash)
                eligible += 1
                row = {{
                    "membership": int(membership),
                    "source_position": int(position),
                    "content_sha256": content_hash,
                    "repo_group_sha256": digest_text(repo),
                    "license_lower": license_name.strip().lower(),
                    "content_chars": int(len(content)),
                    "length_bucket": length_bucket(len(content)),
                }}
                bucket = by_repo[row["repo_group_sha256"]]
                bucket.append(row)
                bucket.sort(key=lambda item: (item["content_sha256"], item["source_position"]))
                del bucket[MAX_PER_REPO:]
            retained = [row for rows in by_repo.values() for row in rows]
            frame = pd.DataFrame(retained)
            if frame.empty:
                raise RuntimeError("no eligible CodeParrot candidates")
            frame = frame.sort_values(
                ["license_lower", "length_bucket", "content_sha256", "source_position"]
            ).reset_index(drop=True)
            if frame.content_sha256.duplicated().any():
                raise RuntimeError("retained content hash duplicate")
            if frame.groupby("repo_group_sha256").size().max() > MAX_PER_REPO:
                raise RuntimeError("repository cap failed")
            return frame, all_hashes, {{
                "scanned_rows": scanned,
                "eligible_unique_content_rows": eligible,
                "retained_rows": len(frame),
                "retained_repositories": int(frame.repo_group_sha256.nunique()),
                "duplicate_content_within_split": duplicates,
            }}

        def capacities(frame):
            counts = frame.groupby(["license_lower", "length_bucket"], sort=True).size()
            return {{(str(license_name), int(bucket)): int(count)
                    for (license_name, bucket), count in counts.items()}}

        def allocation(member_frame, nonmember_frame):
            left = capacities(member_frame)
            right = capacities(nonmember_frame)
            caps = {{key: min(left[key], right[key]) for key in set(left) & set(right)}}
            caps = {{key: value for key, value in caps.items() if value > 0}}
            total = sum(caps.values())
            if total < ROWS_PER_LABEL:
                raise RuntimeError(f"matched capacity too small: {{total}}")
            exact = {{key: ROWS_PER_LABEL * value / total for key, value in caps.items()}}
            out = {{key: min(caps[key], int(math.floor(exact[key]))) for key in caps}}
            remaining = ROWS_PER_LABEL - sum(out.values())
            order = sorted(caps, key=lambda key: (-(exact[key] - math.floor(exact[key])), key[0], key[1]))
            while remaining:
                progressed = False
                for key in order:
                    if out[key] < caps[key]:
                        out[key] += 1
                        remaining -= 1
                        progressed = True
                        if remaining == 0:
                            break
                if not progressed:
                    raise RuntimeError("matched allocation stalled")
            return out, caps

        def select(frame, allocations):
            pieces = []
            for (license_name, bucket), count in sorted(allocations.items()):
                subset = frame[
                    (frame.license_lower == license_name) & (frame.length_bucket == bucket)
                ].sort_values(["content_sha256", "source_position"])
                if len(subset) < count:
                    raise RuntimeError("allocation exceeds capacity")
                pieces.append(subset.head(count))
            return pd.concat(pieces, ignore_index=True)

        def replay(dataset_id, revision, selected, membership, max_rows):
            positions = {{
                int(row.source_position): (str(row.sample_id), str(row.content_sha256))
                for row in selected[selected.membership == membership].itertuples(index=False)
            }}
            found = {{}}
            for position, record in enumerate(stream(dataset_id, revision)):
                if max_rows is not None and position >= max_rows:
                    break
                expected = positions.get(position)
                if expected is None:
                    continue
                content = record.get("content")
                if not isinstance(content, str):
                    raise RuntimeError("selected content disappeared")
                sample_id, expected_hash = expected
                if digest_text(content) != expected_hash or sample_id != f"cp-{{expected_hash}}":
                    raise RuntimeError("selected content replay identity mismatch")
                found[position] = {{
                    "sample_id": sample_id,
                    "content_sha256": expected_hash,
                    "language": "Python",
                    "content": content,
                }}
                if len(found) == len(positions):
                    break
            if len(found) != len(positions):
                raise RuntimeError("selected content replay coverage failed")
            return [found[position] for position in sorted(found)]

        started = time.perf_counter()
        member_candidates, member_hashes, member_diag = scan(
            MEMBER_DATASET, MEMBER_REVISION, 1, TRAIN_SCAN_ROWS
        )
        nonmember_candidates, nonmember_hashes, nonmember_diag = scan(
            NONMEMBER_DATASET, NONMEMBER_REVISION, 0, None
        )
        overlap = member_hashes & nonmember_hashes
        if overlap:
            raise RuntimeError(f"exact content overlap across train/valid source frames: {{len(overlap)}}")
        allocations, caps = allocation(member_candidates, nonmember_candidates)
        members = select(member_candidates, allocations)
        nonmembers = select(nonmember_candidates, allocations)
        if len(members) != ROWS_PER_LABEL or len(nonmembers) != ROWS_PER_LABEL:
            raise RuntimeError("selected label balance failed")
        selected = pd.concat([members, nonmembers], ignore_index=True)
        selected["sample_id"] = "cp-" + selected.content_sha256.astype(str)
        selected["language"] = "Python"
        selected = selected.sort_values("sample_id").reset_index(drop=True)
        if not selected.sample_id.is_unique or selected.content_sha256.duplicated().any():
            raise RuntimeError("final selected identity is not unique")
        if any(value.startswith(("cp-0-", "cp-1-")) for value in selected.sample_id.astype(str)):
            raise RuntimeError("membership leaked into sample ID")
        matched = selected.groupby(
            ["membership", "license_lower", "length_bucket"], sort=True
        ).size().unstack("membership", fill_value=0)
        if set(matched.columns) != {{0, 1}} or not (matched[0].to_numpy() == matched[1].to_numpy()).all():
            raise RuntimeError("train/valid stratum counts are not matched")

        member_rows = replay(MEMBER_DATASET, MEMBER_REVISION, selected, 1, TRAIN_SCAN_ROWS)
        nonmember_rows = replay(NONMEMBER_DATASET, NONMEMBER_REVISION, selected, 0, None)
        prediction_input = pd.DataFrame([*member_rows, *nonmember_rows]).sort_values("sample_id").reset_index(drop=True)
        if len(prediction_input) != 2 * ROWS_PER_LABEL:
            raise RuntimeError("prediction-input row count failed")
        expected_columns = {{"sample_id", "content_sha256", "language", "content"}}
        if set(prediction_input.columns) != expected_columns:
            raise RuntimeError("prediction-input schema changed")
        prediction_input.insert(0, "schema_version", "codeparrot_prediction_input_v1")
        prediction_manifest = prediction_input[["sample_id", "content_sha256", "language"]].copy()
        prediction_manifest.insert(0, "schema_version", "codeparrot_prediction_input_v1")
        prediction_input.to_parquet(OUTPUT / "prediction_input.parquet", index=False)
        prediction_manifest.to_parquet(OUTPUT / "prediction_manifest.parquet", index=False)
        input_sha = sha256((OUTPUT / "prediction_input.parquet").read_bytes()).hexdigest()
        manifest_sha = sha256((OUTPUT / "prediction_manifest.parquet").read_bytes()).hexdigest()
        audit = {{
            "schema_version": "public_codecorpus_matched_cohort_v1",
            "status": "complete_label_free_prediction_input",
            "rows": len(prediction_input),
            "member_source": {{"dataset": MEMBER_DATASET, "revision": MEMBER_REVISION,
                               "rows_scanned": member_diag["scanned_rows"]}},
            "nonmember_source": {{"dataset": NONMEMBER_DATASET, "revision": NONMEMBER_REVISION,
                                  "rows_scanned": nonmember_diag["scanned_rows"]}},
            "member_scan": member_diag,
            "nonmember_scan": nonmember_diag,
            "strata_used": len(allocations),
            "total_matched_capacity": sum(caps.values()),
            "prediction_input_sha256": input_sha,
            "prediction_manifest_sha256": manifest_sha,
            "prediction_columns": prediction_input.columns.tolist(),
            "membership_exported_to_gpu_input": False,
            "evaluation_manifest_exported": False,
            "sample_id_contains_membership": False,
            "private_github_access": False,
            "remote_dataset_code_execution": False,
            "datasets_version": datasets.__version__,
            "wall_seconds": time.perf_counter() - started,
        }}
        (OUTPUT / "cohort_audit.json").write_text(
            json.dumps(audit, indent=2, sort_keys=True) + "\\n", encoding="utf-8"
        )
        print(json.dumps({{
            "status": audit["status"], "rows": audit["rows"],
            "member_scanned": member_diag["scanned_rows"],
            "nonmember_scanned": nonmember_diag["scanned_rows"],
            "prediction_input_sha256": input_sha,
            "membership_exported": False,
            "private_github_access": False,
        }}, sort_keys=True))
        '''
    ).strip()


def compose(output_dir: Path) -> None:
    notebook = nbformat.v4.new_notebook()
    notebook.metadata.kernelspec = {
        "display_name": "Python 3", "language": "python", "name": "python3"
    }
    notebook.metadata.language_info = {"name": "python", "version": "3.12"}
    notebook.cells = [
        nbformat.v4.new_markdown_cell(
            "# Public CodeParrot matched cohort\n\nCPU-only public-data preparation. "
            "Saved prediction input is label-free."
        ),
        nbformat.v4.new_code_cell("%pip install -q datasets==4.8.5 pyarrow pandas"),
        nbformat.v4.new_code_cell(_runtime_cell()),
    ]
    nbformat.validate(notebook)
    code = "\n".join(cell.source for cell in notebook.cells if cell.cell_type == "code")
    if any(token in code for token in FORBIDDEN_PUBLIC_TRANSPORT):
        raise RuntimeError("forbidden GitHub/private transport in public cohort notebook")
    if "evaluation_manifest.parquet" in code or "submission.csv" in code:
        raise RuntimeError("forbidden label/submission artifact in public cohort notebook")
    required = (
        MEMBER_DATASET, MEMBER_REVISION, NONMEMBER_DATASET, NONMEMBER_REVISION,
        "prediction_input.parquet", "membership_exported_to_gpu_input\": False",
        "private_github_access\": False",
    )
    if not all(marker in code for marker in required):
        raise RuntimeError("public cohort notebook contract incomplete")

    output_dir.mkdir(parents=True, exist_ok=True)
    notebook_name = "codeparrot-fresh-cohort-v1.ipynb"
    nbformat.write(notebook, output_dir / notebook_name)
    metadata = {
        "id": TARGET,
        "title": TITLE,
        "code_file": notebook_name,
        "language": "python",
        "kernel_type": "notebook",
        "is_private": True,
        "enable_gpu": False,
        "enable_tpu": False,
        "enable_internet": True,
        "keywords": ["membership-inference", "codeparrot", "cohort"],
        "dataset_sources": [],
        "kernel_sources": [],
        "competition_sources": [],
        "model_sources": [],
    }
    (output_dir / "kernel-metadata.json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(json.dumps({
        "status": "COMPOSE_PASS",
        "target": TARGET,
        "cells": len(notebook.cells),
        "private_github_access": False,
        "membership_exported": False,
    }, sort_keys=True))


def self_test() -> None:
    code = _runtime_cell()
    compile(code, "<public-codecorpus-cohort-runtime>", "exec")
    if any(token in code for token in FORBIDDEN_PUBLIC_TRANSPORT):
        raise RuntimeError("self-test found forbidden private transport")
    if "cp-{membership}" in code or "evaluation_manifest.parquet" in code:
        raise RuntimeError("self-test found label-bearing output contract")
    for marker in (
        MEMBER_REVISION,
        NONMEMBER_REVISION,
        "ROWS_PER_LABEL = 2000",
        "TRAIN_SCAN_ROWS = 500000",
        "prediction_input.parquet",
        "sample_id_contains_membership\": False",
    ):
        if marker not in code:
            raise RuntimeError(f"self-test marker missing: {marker}")
    print("PUBLIC_CODECORPUS_COHORT_SELF_TEST PASS private_repo_access=0 membership_exported=0")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--output-dir", type=Path)
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return 0
    if args.output_dir is None:
        parser.error("--output-dir is required unless --self-test is used")
    compose(args.output_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
